[pytest]
testpaths = tests/
pythonpath = .

addopts =
    -v
    --tb=short
    --base-url=http://localhost:8006/
    --html=reports/report.html
    --self-contained-html

python_files = test_*.py
python_functions = test_*

markers =
    smoke: testes rápidos
    regression: testes completos

asyncio_mode = strict